/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: commands.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as commands_pb from './commands_pb'; // proto import: "commands.proto"


export class CommandsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUnaryRPC = new grpcWeb.MethodDescriptor(
    '/proto.Commands/UnaryRPC',
    grpcWeb.MethodType.UNARY,
    commands_pb.UnaryRequest,
    commands_pb.UnaryResponse,
    (request: commands_pb.UnaryRequest) => {
      return request.serializeBinary();
    },
    commands_pb.UnaryResponse.deserializeBinary
  );

  unaryRPC(
    request: commands_pb.UnaryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<commands_pb.UnaryResponse>;

  unaryRPC(
    request: commands_pb.UnaryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: commands_pb.UnaryResponse) => void): grpcWeb.ClientReadableStream<commands_pb.UnaryResponse>;

  unaryRPC(
    request: commands_pb.UnaryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: commands_pb.UnaryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.Commands/UnaryRPC',
        request,
        metadata || {},
        this.methodDescriptorUnaryRPC,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.Commands/UnaryRPC',
    request,
    metadata || {},
    this.methodDescriptorUnaryRPC);
  }

  methodDescriptorServerStreamRPC = new grpcWeb.MethodDescriptor(
    '/proto.Commands/ServerStreamRPC',
    grpcWeb.MethodType.SERVER_STREAMING,
    commands_pb.ServerStreamRequest,
    commands_pb.ServerStreamResponse,
    (request: commands_pb.ServerStreamRequest) => {
      return request.serializeBinary();
    },
    commands_pb.ServerStreamResponse.deserializeBinary
  );

  serverStreamRPC(
    request: commands_pb.ServerStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<commands_pb.ServerStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/proto.Commands/ServerStreamRPC',
      request,
      metadata || {},
      this.methodDescriptorServerStreamRPC);
  }

}

